steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -f
      - Dockerfile.web
      - -t
      - $_IMAGE
      - .
images:
  - $_IMAGE
options:
  logging: CLOUD_LOGGING_ONLY



