FROM node:20-bookworm-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci --include=dev

COPY . .

ENV NODE_ENV=production
EXPOSE 8080

CMD ["npm", "run", "socket"]

