FROM node:20-bookworm-slim

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

RUN apt-get update -y && apt-get install -y openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma

RUN npm ci --include=dev

COPY . .

RUN npm run build

ENV NODE_ENV=production
EXPOSE 8080

CMD ["npm", "run", "start", "--", "--hostname", "0.0.0.0"]

